"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
Packages = ['pylogrus','requests']
APP = ['intrusiondetection.py']
DATA_FILES = ['com.datadog.intrusiondetection.plist']

setup(
    app=APP,
    data_files=DATA_FILES,
    options=dict(py2app=dict(plist='com.datadog.intrusiondetection.plist')),
    setup_requires=['py2app'],
)
